name: Trigger auto deployment for app2323232

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/app/**'
    - '.github/workflows/app2323232-AutoDeployTrigger-51a4d423-c804-461d-bdfc-a9807f52afcd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APP2323232_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APP2323232_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APP2323232_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/app 
          registryUrl: containerregistryvoj5arwja3y5y.azurecr.io
          registryUsername: ${{ secrets.APP2323232_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APP2323232_REGISTRY_PASSWORD }}
          containerAppName: app2323232
          resourceGroup: jamstack1ba97
          imageToBuild: containerregistryvoj5arwja3y5y.azurecr.io/app2323232:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


